# filepath: d:\Code\discord-music-bot\nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20", "python3", "ffmpeg", "yt-dlp"]

[phases.install] 
cmds = [
  "pip3 install --upgrade yt-dlp",
  "npm ci"
]

[start]
cmd = "node index.js"