# filepath: d:\Code\discord-music-bot\nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip", "ffmpeg", "yt-dlp"]

[phases.install] 
cmds = ["npm ci"]

[start]
cmd = "node index.js"